# Generated by Django 3.0.7 on 2020-07-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='example', max_length=100),
        ),
    ]
