# Generated by Django 3.0.7 on 2020-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200707_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='Код продукта')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('tea_color', models.CharField(choices=[('G', 'Green'), ('B', 'Black'), ('R', 'Red')], default='B', max_length=1, verbose_name='Цвет')),
                ('count', models.PositiveIntegerField(verbose_name='Колличество')),
                ('price', models.FloatField(max_length=1000.0, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
